plugins {
    id 'com.android.application' version '9.2.0'
}

android {
    namespace 'docencia.xaviersastre.taskmanager'
    compileSdk 34

    defaultConfig {
        applicationId "docencia.xaviersastre.taskmanager"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    buildFeatures {
        viewBinding true
    }

    // Adjusting for non-standard project structure
    sourceSets {
        main {
            manifest.srcFile 'AndroidManifest.xml'
            java.srcDirs = ['src/main/java']
            res.srcDirs = ['res']
        }
    }
}

dependencies {
    implementation 'androidx.core:core-ktx:1.12.0'
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.11.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation 'androidx.recyclerview:recyclerview:1.3.2'
    implementation 'androidx.fragment:fragment:1.6.2'
    implementation 'androidx.localbroadcastmanager:localbroadcastmanager:1.1.0'
}
